### ISSUE TITLE
animation callbacks

### ISSUE THREAD

**Issue by vitobellini** [cocoatoucher/AIFlatSwitch#1]
Hello, it would be nice to have a callback blocs for animation did start and animation did end.
What do you think? I have to address this scenario:

I've got the switches tableview's rows, and when the switch changes from off to on, I have to reorder the table, but the animation during the reording is not fine.

**Comment by cocoatoucher** [comment]
Hi @Progeny can you attach a video for this scenario, or some screenshots, I might have a better solution for it. Thanks

**Comment by the-freshlord** [comment]
I also have this issue as well. Now if I save the position, the animation doesn't even work.

**Comment by cocoatoucher** [comment]
Thanks! Having a second look now, I can understand this issue. I'll add some callback for animation did end.

**Comment by cocoatoucher** [comment]
Added animation callback closures in 1.0.5 👍
Let me know if it works for you guys
