### ISSUE TITLE
Cant change the selected state

### ISSUE THREAD

**Issue by ChetanRajagiri** [cocoatoucher/AIFlatSwitch#14]
![screen shot 2017-07-11 at 10 07 28 pm](https://user-images.githubusercontent.com/16207507/28079316-7c47637c-6685-11e7-9b57-33d5a98ec83d.png)
![screen shot 2017-07-11 at 10 08 19 pm](https://user-images.githubusercontent.com/16207507/28079317-7c8c7e8a-6685-11e7-8a73-d033096c8a99.png)

It worked in one sample project but not working on the other project..
What might have gone wrong?

**Comment by cocoatoucher** [comment]
Hey what Xcode version is this?

**Comment by ChetanRajagiri** [comment]
Its 8.3.2
Its not working when we use the IB builder, but worked when done programmatically.

**Comment by wdcurry** [comment]
... "Failed to set (isSelected) user defined inspected property on (AIFlatSwitch.AIFlatSwitch): [<AIFlatSwitch.AIFlatSwitch 0x7fdd9eb03540> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key isSelected."

**Comment by cocoatoucher** [comment]
Hey I still have no idea how this happens, works fine for the other properties like trailColor. Spent some time on it but no solution 🤷‍♂️ Might be an IB bug?
Good thing is you still have workaround from the code

**Comment by wdcurry** [comment]
It likely relates to the fact that setting this causes the animation to run inside IB.
