### ISSUE TITLE
Inner circle color

### ISSUE THREAD

**Issue by Maryom** [cocoatoucher/AIFlatSwitch#16]
Hey,

Thanks for your work.

Is there a way to set a color just for the inner circle?

**Comment by cocoatoucher** [comment]
Hi, I'm afraid this is not possible with the current version but it can be an improvement.
For now, I can recommend adding an empty and coloured UIView with its layer's corners rounded as a circle behind the switch.

**Comment by Maryom** [comment]
Ok thanks.

**Comment by cocoatoucher** [comment]
Would you like to make this change and contribute though? You are more than welcome if so :) If not, I don't have much time nowadays, but I can fix that after a week or so
