### ISSUE TITLE
Min Deployment Target 8.0 = Warning in Xcode

### ISSUE THREAD

**Issue by nilsnilsnils** [cocoatoucher/AIFlatSwitch#19]
AIFlatSwitch/Package.swift The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99.

Maybe someone can set the min version for iOS to 9.0 ? :) Thanks

**Comment by cocoatoucher** [comment]
This is fixed in release `1.0.8` now 🎉
