### ISSUE TITLE
Tap event not working in Swift 1.3

### ISSUE THREAD

**Issue by rishimukherjee** [cocoatoucher/AIFlatSwitch#5]
The function `onTouchUpInside` is not getting called. I am making the switch programmatically. I am using Swift 1.3. Could not understand why it is not working. Please help!

**Comment by cocoatoucher** [comment]
it should be working with value changed event as designed

**Comment by wdcurry** [comment]
A note: if you add a tap to the main view in order to create a general keyboard dismissal, the swtich will not register the tap and a tap gesture must be added back in with a call to negate the current value of the switch. A simple .toggle() would be sweet.
